### PR TITLE
fix:修复spawn中不支持win32平台的bug(#57)

### LINKED ISSUE #57: packages/core/src/utils/dependenciesInstall.ts 中 spqwn 不支持 win32 的 bug 修复

### PR DESCRIPTION
**Pull request by qq1051766345**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[✅] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
- Closes #57 
- Related #24 

## What is the new behavior?

修复spawn中不支持win32平台的bug

## Does this PR introduce a breaking change?

```
[ ] Yes
[✅] No
```

### CODE REVIEW

**Review by uaenaTzx — APPROVED** [review]

File: packages/core/src/index.ts [hunk 1]
```diff
@@ -7,6 +7,9 @@ import minimist from "minimist";
 import { getPackageJsonInfo, createApp } from "./utils";
 import createAppTest from "./utils/createAppTest";
 
+// todo 防止报错
+console.log(createApp);
```
Comment (xun082) [inline packages/core/src/index.ts:11]: 这个打印删了，对于导入了并没有使用的变量直接删掉，下面的也是，console.log(execSync);这个
